spring.application.name=app

# Mistral AI Configuration
spring.ai.mistralai.api-key=${API_KEY}
spring.ai.mistralai.chat.options.model=open-mistral-nemo
spring.ai.guardrails.enabled=false

# PostgreSQL Database Configuration for Supabase
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Timezone configuration
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# XSS Protection
server.servlet.session.cookie.http-only=true

# Micrometer Tracing Configuration
management.tracing.sampling.probability=1.0

# Logging configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS, UTC}Z %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n
